In [3]:
#Logistic Regression
'''it's conducted when there is only two possibility of outcome e.g Binomial Distribution'''


"it's conducted when there is only two possibility of outcome e.g Binomial Distribution"

In [4]:
import numpy as np
from sklearn.linear_model import LogisticRegression


In [5]:
#X represents the size of a tumor in centimeters.

X = np.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)

 #Note: X has to be reshaped into a column from a row for the LogisticRegression() function to work.
#y represents whether or not the tumor is cancerous (0 for "No", 1 for "Yes").

#y represents whether or not the tumor is cancerous (0 for "No", 1 for "Yes").

y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1]) 

In [6]:
#FITTING THE LOGISTIC MODEL
model=LogisticRegression()
model.fit(X,y)

LogisticRegression()

In [7]:
#predict if tumor is cancerous where the size is 3.46mm:
predicted_value = model.predict(np.array([3.46]).reshape(-1,1))
predicted_value

array([0])

In [8]:
'''We have predicted that a tumor with a size of 3.46mm will not be cancerous.'''

'We have predicted that a tumor with a size of 3.46mm will not be cancerous.'

In [9]:
#COEFFICIENT
''' The coefficient explains what happens when there is a change in the size of the tumor;
whether it would be cancerous or not'''

' The coefficient explains what happens when there is a change in the size of the tumor;\nwhether it would be cancerous or not'

In [ ]:
#Determining the coefficient
log_odds = model.coef_
odds=np.exp(log_odds)
odds

#NOTE: YOU CAN either change  to odds or leave it in log_odds, either way works but explanation changes.


array([[4.03541657]])

In [11]:
'''the array([[4.03541657]]) implies that if the tumor size increases by 1mm the odds of it being a cancerous tumor
increases by 4x.'''

'the array([[4.03541657]]) implies that if the tumor size increases by 1mm the odds of it being a cancerous tumor\nincreases by 4x.'

In [12]:
#PROBABILITY
'''The coefficient and intercept values can be used to find the probability that each tumor is cancerous.

Create a function that uses the model's coefficient and intercept values to return a new value. 
This new value represents probability that the given observation is a tumor:'''

"The coefficient and intercept values can be used to find the probability that each tumor is cancerous.\n\nCreate a function that uses the model's coefficient and intercept values to return a new value. \nThis new value represents probability that the given observation is a tumor:"

In [13]:
def logistic2probability(model,X):
    log_odds = model.coef_ *X + model.intercept_
    odds=np.exp(log_odds)
    probability = odds/(1+odds)
    return(probability)
print(logistic2probability(model,X))

[[0.60749955]
 [0.19268876]
 [0.12775886]
 [0.00955221]
 [0.08038616]
 [0.07345637]
 [0.88362743]
 [0.77901378]
 [0.88924409]
 [0.81293497]
 [0.57719129]
 [0.96664243]]


In [14]:
#EXPLAINING THE ABOVE RESULTS
'''3.78 0.61 The probability that a tumor with the size 3.78cm is cancerous is 61%.'''

'''2.44 0.19 The probability that a tumor with the size 2.44cm is cancerous is 19%.'''

'''2.09 0.13 The probability that a tumor with the size 2.09cm is cancerous is 13%.'''

'2.09 0.13 The probability that a tumor with the size 2.09cm is cancerous is 13%.'

In [15]:
        '''KEEP BUILDING,BUILDERS NEVER STOP'''

'KEEP BUILDING,BUILDERS NEVER STOP'